package quiz.ui;

import quiz.model.ResultadoQuiz;
import quiz.dao.ResultadoQuizDAO;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import quiz.model.Usuario;
import quiz.service.QuizService;
import quiz.service.PerguntaQuiz;
import quiz.model.Capital;

public class QuizForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(QuizForm.class.getName());
    private QuizService quizService;
    private PerguntaQuiz perguntaAtual;
    private int pontuacao = 0;
    private int perguntaAtualNumero = 0;
    private static final int TOTAL_PERGUNTAS = 15;
    private Usuario usuarioLogado;

    /**
     * Creates new form Quiz
     */
    public QuizForm(Usuario usuario) {
    initComponents();
    jProgressPerguntas.setMinimum(0);
    jProgressPerguntas.setMaximum(TOTAL_PERGUNTAS);
    jProgressPerguntas.setValue(0);
    jProgressPerguntas.setStringPainted(true);
    this.usuarioLogado = usuario;
    quizService = new QuizService();
    carregarPergunta();
}
    
    
    private void carregarPergunta() {

    if (perguntaAtualNumero >= TOTAL_PERGUNTAS) {
        salvarPontuacao();
        JOptionPane.showMessageDialog(
            this,
            "Fim do jogo!\nPontuação: " + pontuacao + "/" + TOTAL_PERGUNTAS
        );
        this.dispose();
    new LoginForm().setVisible(true);
        return;
    }

    perguntaAtual = quizService.gerarPerguntaCapitalFederal();

    if (perguntaAtual == null) {
        JOptionPane.showMessageDialog(this, "Sem perguntas disponíveis.");
        this.dispose();
    new LoginForm().setVisible(true);
        return;
    }

    jlblPergunta.setText(perguntaAtual.getEnunciado());

    if (perguntaAtual.getAlternativas().size() < 4) {
    JOptionPane.showMessageDialog(
        this,
        "Erro: pergunta com menos de 4 alternativas."
    );
    this.dispose();
    new LoginForm().setVisible(true);
    return;
}

// só depois disso pode acessar os índices
jbttA.setText(perguntaAtual.getAlternativas().get(0).getNome());
jbttB.setText(perguntaAtual.getAlternativas().get(1).getNome());
jbttC.setText(perguntaAtual.getAlternativas().get(2).getNome());
jbttD.setText(perguntaAtual.getAlternativas().get(3).getNome());
}


    private void atualizarProgresso() {
    jProgressPerguntas.setValue(perguntaAtualNumero);
    jProgressPerguntas.setString(
        perguntaAtualNumero + " / " + TOTAL_PERGUNTAS
    );
}

        private void verificarResposta(int indiceEscolhido) {

    Capital escolhida = perguntaAtual.getAlternativas().get(indiceEscolhido);

    if (perguntaAtual.verificarResposta(escolhida)) {
        pontuacao++;
        JOptionPane.showMessageDialog(this, "✅ Resposta correta!");
    } else {
        JOptionPane.showMessageDialog(
            this,
            "❌ Resposta errada!\nResposta correta: " +
            perguntaAtual.getCorreta().getNome()
        );
    }

    // AVANÇA SEMPRE
    perguntaAtualNumero++;
    atualizarProgresso();
    carregarPergunta();
}


private void salvarPontuacao() {
    ResultadoQuiz resultado = new ResultadoQuiz();
    resultado.setUsuario(usuarioLogado);
    resultado.setPontuacao(pontuacao);
    resultado.setData(LocalDateTime.now());

    ResultadoQuizDAO dao = new ResultadoQuizDAO();
    dao.salvar(resultado);
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlblPergunta = new javax.swing.JLabel();
        jbttC = new javax.swing.JButton();
        jbttA = new javax.swing.JButton();
        jbttD = new javax.swing.JButton();
        jbttB = new javax.swing.JButton();
        jbttSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jProgressPerguntas = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 102, 255));

        jlblPergunta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jbttC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttCActionPerformed(evt);
            }
        });

        jbttA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttAActionPerformed(evt);
            }
        });

        jbttD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttDActionPerformed(evt);
            }
        });

        jbttB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbttA, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jlblPergunta))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbttB, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbttC, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jbttD, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlblPergunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbttA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbttB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbttC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbttD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jbttSair.setBackground(new java.awt.Color(255, 255, 255));
        jbttSair.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jbttSair.setForeground(new java.awt.Color(0, 0, 0));
        jbttSair.setText("Sair");
        jbttSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttSairActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Quiz");

        jProgressPerguntas.setBackground(new java.awt.Color(255, 255, 255));
        jProgressPerguntas.setForeground(new java.awt.Color(51, 51, 51));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Users\\freit\\Downloads\\bandeiras.png")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Users\\freit\\OneDrive\\Alvi\\terra.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressPerguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbttSair, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jProgressPerguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jbttSair)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbttBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttBActionPerformed
        verificarResposta(1);
    }//GEN-LAST:event_jbttBActionPerformed

    private void jbttAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttAActionPerformed
        verificarResposta(0);
    }//GEN-LAST:event_jbttAActionPerformed

    private void jbttCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttCActionPerformed
        verificarResposta(2);
    }//GEN-LAST:event_jbttCActionPerformed

    private void jbttDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttDActionPerformed
        verificarResposta(3);
    }//GEN-LAST:event_jbttDActionPerformed

    private void jbttSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttSairActionPerformed
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_jbttSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressPerguntas;
    private javax.swing.JButton jbttA;
    private javax.swing.JButton jbttB;
    private javax.swing.JButton jbttC;
    private javax.swing.JButton jbttD;
    private javax.swing.JButton jbttSair;
    private javax.swing.JLabel jlblPergunta;
    // End of variables declaration//GEN-END:variables
}
