
package quiz.ui;

import javax.swing.JOptionPane;
import quiz.model.Usuario;
import quiz.repository.impl.UsuarioRepositoryJPA;
import quiz.service.AutenticacaoService;

/**
 * Tela de login. Depois da refatoração, esta classe cuida apenas de
 * capturar os campos digitados e reagir a eventos de UI; toda a regra
 * de "quem pode entrar" foi movida para AutenticacaoService (SRP).
 *
 * @author freit
 */
public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());
    private Usuario usuario;
    private final AutenticacaoService autenticacaoService;
    
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        this(new AutenticacaoService(new UsuarioRepositoryJPA()));
    }

    /**
     * Construtor com injeção de dependência: permite passar um
     * AutenticacaoService construído com um repositório diferente
     * (por exemplo, um repositório em memória em testes) sem alterar
     * esta classe.
     */
    public LoginForm(AutenticacaoService autenticacaoService) {
        this.autenticacaoService = autenticacaoService;
        initComponents();
        jlblLogin.requestFocus();
    }
    
    private void autenticar() {
    String login = jtxtLogin.getText();
    String senha = new String(jtxtSenha.getPassword());

    this.usuario = autenticacaoService.autenticar(login, senha);

    if (this.usuario == null) {
        JOptionPane.showMessageDialog(this,
            "Usuário ou senha inválidos",
            "Erro",
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (autenticacaoService.isJogador(this.usuario)) {
        new QuizForm(this.usuario).setVisible(true);
    } else if (autenticacaoService.isAdministrador(this.usuario)) {
        new AdminForm(this.usuario).setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this,
            "Tipo de usuário inválido: " + this.usuario.getTipo());
        return;
    }

    this.dispose();
}

    /**
     * Carrega um ícone do classpath (src/main/resources) em vez de um
     * caminho absoluto do disco. Se o arquivo não existir, a tela
     * simplesmente fica sem aquele ícone, em vez de lançar exceção.
     */
    private void setIconeSeDisponivel(javax.swing.JLabel label, String caminhoClasspath) {
        java.net.URL url = getClass().getResource(caminhoClasspath);
        if (url != null) {
            label.setIcon(new javax.swing.ImageIcon(url));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlblLogin = new javax.swing.JLabel();
        jlblSenha = new javax.swing.JLabel();
        jtxtLogin = new javax.swing.JTextField();
        jtxtSenha = new javax.swing.JPasswordField();
        jlblTitulo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jbttLogin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jlblCopyright = new javax.swing.JLabel();
        jbttNovoCadastro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)));

        jlblLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblLogin.setForeground(new java.awt.Color(0, 0, 0));
        jlblLogin.setText("Login:");

        jlblSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblSenha.setForeground(new java.awt.Color(0, 0, 0));
        jlblSenha.setText("Senha:");

        jtxtLogin.setBackground(new java.awt.Color(204, 204, 204));
        jtxtLogin.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jtxtLogin.setForeground(new java.awt.Color(0, 0, 0));
        jtxtLogin.setBorder(new javax.swing.border.MatteBorder(null));
        jtxtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLoginActionPerformed(evt);
            }
        });

        jtxtSenha.setBackground(new java.awt.Color(204, 204, 204));
        jtxtSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtSenha.setForeground(new java.awt.Color(0, 0, 0));
        jtxtSenha.setBorder(new javax.swing.border.MatteBorder(null));

        jlblTitulo.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jlblTitulo.setText("Bem Vindo ao Quiz Capitais Globais");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 255));

        jbttLogin.setBackground(new java.awt.Color(0, 0, 0));
        jbttLogin.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbttLogin.setForeground(new java.awt.Color(255, 255, 255));
        jbttLogin.setText("Entrar");
        jbttLogin.setBorder(null);
        jbttLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttLoginActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 204));

        jlblCopyright.setForeground(new java.awt.Color(0, 0, 0));
        jlblCopyright.setText("© 2026 – Quiz Capitais Globais");

        jbttNovoCadastro.setBackground(new java.awt.Color(255, 255, 255));
        jbttNovoCadastro.setForeground(new java.awt.Color(51, 102, 255));
        jbttNovoCadastro.setText("Não tem uma conta? Cadastre-se");
        jbttNovoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttNovoCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jlblTitulo)
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jbttLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblLogin)
                    .addComponent(jlblSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtSenha)
                    .addComponent(jtxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblCopyright)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbttNovoCadastro)
                .addGap(236, 236, 236))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jlblLogin)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSenha)
                    .addComponent(jtxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbttNovoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbttLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jlblCopyright)
                .addContainerGap())
        );

        // Antes: caminhos absolutos do disco local do autor
        // ("D:\Users\freit\..."), que só funcionavam na máquina onde o
        // projeto foi criado (code smell: hardcoded/environment-specific
        // path). Agora os ícones são carregados do classpath
        // (src/main/resources/images), então funcionam em qualquer
        // máquina que rode o projeto.
        setIconeSeDisponivel(jLabel3, "/images/bandeiras.png");
        setIconeSeDisponivel(jLabel4, "/images/terra.png");
        setIconeSeDisponivel(jLabel6, "/images/terra.png");
        setIconeSeDisponivel(jLabel7, "/images/bandeiras.png");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbttLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttLoginActionPerformed
        autenticar();
    }//GEN-LAST:event_jbttLoginActionPerformed

    private void jtxtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLoginActionPerformed

    private void jbttNovoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttNovoCadastroActionPerformed
        // Antes: "new CadastroForm(this.usuario)" enviava sempre null,
        // pois nesse ponto ninguém havia efetuado login ainda. O
        // parâmetro nunca era usado dentro de CadastroForm (dead code),
        // então foi removido do construtor.
        new CadastroForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbttNovoCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // O ponto de entrada oficial da aplicação passou a ser
        // quiz.app.QuizApp (composition root), que monta os
        // repositórios/serviços e então abre esta tela. Este main()
        // aqui foi mantido só para permitir abrir a LoginForm
        // isoladamente durante o desenvolvimento/testes manuais de UI.
        quiz.app.QuizApp.main(args);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbttLogin;
    private javax.swing.JButton jbttNovoCadastro;
    private javax.swing.JLabel jlblCopyright;
    private javax.swing.JLabel jlblLogin;
    private javax.swing.JLabel jlblSenha;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JTextField jtxtLogin;
    private javax.swing.JPasswordField jtxtSenha;
    // End of variables declaration//GEN-END:variables
}
